{% set name = "globus-sdk" %}
{% set version = "3.56.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3a794106136f3d43505bb2fede3e81a63735d608a812d11338135126a857e7ca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.2
  run:
    - python >={{ python_min }}
    - cryptography >=3.3.1,!=3.4.0
    - pyjwt >=2.0.0,<3.0.0
    # pyjwt[crypto] has different constraints on cryptography depending on the version
    - requests >=2.19.1,<3.0.0
    # from upstream, this is only for py<3.11 but we'll try to keep this noarch
    - typing_extensions >=4.0

test:
  imports:
    - globus_sdk
    - globus_sdk.authorizers
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/globus/globus-sdk-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Globus SDK for Python
  description: This SDK provides a convenient Pythonic interface to Globus APIs.
  doc_url: http://globus-sdk-python.readthedocs.io/
  dev_url: https://github.com/globus/globus-sdk-python

extra:
  recipe-maintainers:
    - xylar
